jobs:
- job: Build_Job
  displayName: Build Job
  pool:
    vmImage: $(vmImageName)
  steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(nameLessThan15)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      buildContext: .
      tags: |
        $(tag)

  - publish: manifests
    artifact: manifests